---
- name: install phpMyAdmin
  yum:
    name: phpMyAdmin
    state: latest
- name: create phpMyAdmin config file
  template:
    src: config.inc.php.j2
    dest: /etc/phpMyAdmin/config.inc.php
- name: create phpMyAdmin upload directory
  file:
    dest: "{{ phpmyadmin_upload_dir }}"
    state: directory
    mode: 0750
    group: apache
    owner: apache
- name: create phpMyAdmin save directory
  file:
    dest: "{{ phpmyadmin_save_dir }}"
    state: directory
    mode: 0750
    group: apache
    owner: apache
- name: remove apache phpMyAdmin config file
  file:
    path: /etc/httpd/conf.d/phpMyAdmin.conf
    state: absent
