---
- name: install dependency packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ lexicon_dependency_packages }}"
- name: install dependency pip lexicon
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ lexicon_dependency_pip_packages }}"
- name: install lexicon
  pip:
    name: dns-lexicon
    state: latest
- name: check installd dehydrated
  stat:
    path: /etc/dehydrated
  register: result
- block:
  - name: create hook script directory
    file:
      path: /etc/dehydrated/hooks
      state: directory
  - name: get dehydrated hook script
    get_url:
      url: https://raw.githubusercontent.com/AnalogJ/lexicon/master/examples/dehydrated.default.sh
      dest: /etc/dehydrated/hooks/lexicon
  when: result.stat.exists
